export { default as HomeScr } from "./home/home";
export { default as SinglePlayerGameScr } from "./single-player-game/single-player-game";
export { default as SettingsScr } from "./settings/settings";
export { default as LoginScr } from "./login/login";
export { default as SignUpScr } from "./signup/signup";
export { default as ChangePasswordScr } from "./change-password/change-password";
export { default as ForgotPasswordScr } from "./forgot-password/forgot-password";
export { default as MultiplayerHomeScr } from "./multiplayer-home/multiplayer-home";
export { default as MultiplayerGameScr } from "./multiplayer-game/multiplayer-game";
